sudo: false
language: python
services:
- memcached
python:
- '2.7'
install:
- echo "0.01" > restclients/VERSION
- if [[ $DJANGO_VERSION == 1.6 ]]; then pip install -r travis-ci/python-2.6-require-django-1.6.txt;
  fi
- pip install -e .
env:
- DJANGO_VERSION=1.6.*
- DJANGO_VERSION=1.7.*
- DJANGO_VERSION=1.8.*
- DJANGO_VERSION=1.9.*
- DJANGO_VERSION=1.10.*
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pep8
- pip install -U "Django==$DJANGO_VERSION"
- cp travis-ci/manage.py manage.py
- if [[ $DJANGO_VERSION != 1.6* ]]; then python manage.py migrate --noinput; fi
- if [[ $DJANGO_VERSION == 1.6* ]]; then python manage.py syncdb --noinput; fi
script:
- pep8 --exclude=migrations,restclients/sws/,restclients/canvas/,restclients/uwnetid/,restclients/test/,restclients/signals/,restclients/hfs/,restclients/r25,restclients/o365/,restclients/nws.py,restclients/sms.py,restclients/library/
  restclients/
- python -m compileall restclients/
- coverage run --source=restclients manage.py test restclients
after_script:
- coveralls
before_deploy:
- find restclients/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > restclients/VERSION
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: jsTm65lB9zSlAGFdCgTIUiZF0ZpVM0QFUq2qVaHwV0yiXH+46HcSoaLFFIA4NjjuN7mpU//wnnUEO5j9BORsSVCbKSbCTLy8g63u/RIpRQN2GLSm7hD8NcM7peOtxwouqaZ6zWvPB3jeqN1CZTtmbXvEsstvdfuedvO6nCsDs5M=
  on:
    tags: true
    python: '2.7'
    condition: 1.10 = $DJANGO_VERSION
